/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Juego;

import javax.swing.JOptionPane;

/**
 *
 * @author digital
 */
public class Login extends javax.swing.JFrame {
    String Registro;
    int TipoVentana;
    /**
     * Creates new form Login
     */
    public Login(int Tipe) {
        initComponents();
        this.TipoVentana=Tipe;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Nombre");

        jLabel2.setText("Codigo");

        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField1KeyTyped(evt);
            }
        });

        jTextField2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField2KeyTyped(evt);
            }
        });

        jButton1.setText("Ingresar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jTextField2)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(102, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    // TODO add your handling code here:
        if (jTextField1.getText().compareTo("")!=0 && jTextField2.getText().compareTo("")!=0) {
        Registro = jTextField1.getText() + "-" + jTextField2.getText();
        ControladorArchivo C = new ControladorArchivo(System.getProperty("user.dir") + "/src/juego/ArchivosJuego/UsuariosJuego.txt");
        boolean sw = C.BuscarArchivo(Registro);
            if (sw==true) {
                if (TipoVentana==1) {
                  JOptionPane.showMessageDialog(null,"El usuario ya se encuentra registrado","Nombre Juego",JOptionPane.WARNING_MESSAGE);
                }else{
                 JOptionPane.showMessageDialog(null,"Bienvenido al -Nombre Juego- " + jTextField1.getText(),"Nombre Juego" + jTextField1.getText()  ,JOptionPane.WARNING_MESSAGE);
                     Inicial Ini = new Inicial(true);
                     setVisible(false);
                     Ini.setVisible(true);
                     Ini.setLocationRelativeTo(null);
                }
            }else{
               if (TipoVentana==1) {
                  JOptionPane.showMessageDialog(null,"Registro completado.","Nombre Juego.",JOptionPane.WARNING_MESSAGE);
                  C.EscribirArchivo(Registro);
                  Inicial Ini = new Inicial(true);
                  setVisible(false);
                  Ini.setVisible(true);
                  Ini.setLocationRelativeTo(null);
                }else{
                 JOptionPane.showMessageDialog(null,"El usuario " +  jTextField1.getText()  + "Código "+ jTextField2.getText() + " no existe en sistema.","Nombre Juego" ,JOptionPane.WARNING_MESSAGE);
                }
            }
        }else{
         JOptionPane.showMessageDialog(null,"Llene todos los campos de registro.","Nombre Juego" + jTextField1.getText()  ,JOptionPane.WARNING_MESSAGE);
        }
    
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyTyped
        // TODO add your handling code here:
        int NumCa=30;
        if (jTextField1.getText().length() >= NumCa) {
            getToolkit().beep(); 
            evt.consume();
            //JOptionPane.showMessageDialog(rootPane,"Minimo");
        }
    }//GEN-LAST:event_jTextField1KeyTyped

    private void jTextField2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField2KeyTyped
        // TODO add your handling code here:
               int NumCa=10;
        if (jTextField2.getText().length() >= NumCa) {
            getToolkit().beep(); 
            evt.consume();
            //JOptionPane.showMessageDialog(rootPane,"Minimo");
        }else{
         char c=evt.getKeyChar(); 
             
         
          if(!Character.isDigit(c)) { 
              //getToolkit().beep(); 
              evt.consume(); 
              //JOptionPane.showMessageDialog(rootPane,"Solo se permiten datos numericos.");
               
          } 
        }
    }//GEN-LAST:event_jTextField2KeyTyped

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
